/***
 * @module Hypotrochoid
 * @brief Rolling-circle hypotrochoid geometry for non-circular gears.
 *
 * The curve is generated by a point on a circle rolling inside a fixed
 * circle. The documented ratio constraints reject cusp and loop cases.
 */
include <../trochoid/base.scad>

function _cg_hypotrochoid_point(R,r,d,theta) = [(R-r)*cos(theta)+d*cos((R-r)/r*theta),(R-r)*sin(theta)-d*sin((R-r)/r*theta)];
function _cg_hypotrochoid_points(R,r,d,n=720) = [for(i=[0:n-1]) _cg_hypotrochoid_point(R,r,d,360*i/n)];
function _cg_hypotrochoid_scale(modul,tooth_number,R=3,r=1,d=.35,n=720) = _cg_trochoid_scale_from_points(modul,tooth_number,_cg_hypotrochoid_points(R,r,d,n));
function _cg_hypotrochoid_radius(R,r,d,theta) = _cg_trochoid_radius_from_point(_cg_hypotrochoid_point(R,r,d,theta));
function _cg_hypotrochoid_curve_radius(scale,R,r,d,theta) = _cg_trochoid_curve_radius_from_point(scale,_cg_hypotrochoid_point(R,r,d,theta));
function _cg_hypotrochoid_points_scaled(scale,R,r,d,n=720) = _cg_trochoid_points_scaled_from_points(scale,_cg_hypotrochoid_points(R,r,d,n));
