/***
 * @module Epitrochoid
 * @brief Rolling-circle epitrochoid geometry for non-circular gears.
 *
 * The curve is generated by a point on a rolling circle:
 * `x=(R+r)cos(theta)-d cos((R+r)theta/r)` and
 * `y=(R+r)sin(theta)-d sin((R+r)theta/r)`. The documented ratio constraints
 * reject cusp and loop cases; high curvature may require more samples.
 * Reference: https://encyclopediaofmath.org/wiki/Epitrochoid.
 */
include <../trochoid/base.scad>

// Public-family aliases over the shared trochoid implementation. Keeping the
// family names here preserves the internal contracts used by mate generation.
/***
 * @function _cg_epitrochoid_point(R, r, d, theta)
 * @brief Evaluate one point on the unit rolling-circle epitrochoid.
 * @param R {number > 0} Fixed-circle ratio.
 * @param r {number > 0} Rolling-circle ratio.
 * @param d {number >= 0} Pen offset ratio.
 * @param theta {angle} Curve parameter in degrees.
 * @return {array} Cartesian point `[x, y]` in unit-curve coordinates.
 */
function _cg_epitrochoid_point(R,r,d,theta) = [(R+r)*cos(theta)-d*cos((R+r)/r*theta),(R+r)*sin(theta)-d*sin((R+r)/r*theta)];
/***
 * @function _cg_epitrochoid_points(R, r, d, n)
 * @brief Sample one complete unit epitrochoid curve.
 * @param R {number > 0} Fixed-circle ratio.
 * @param r {number > 0} Rolling-circle ratio.
 * @param d {number >= 0} Pen offset ratio.
 * @param n {integer >= 1, default 720} Number of samples.
 * @return {array} Closed list of sampled Cartesian points.
 */
function _cg_epitrochoid_points(R,r,d,n=720) = [for(i=[0:n-1]) _cg_epitrochoid_point(R,r,d,360*i/n)];
/***
 * @function _cg_epitrochoid_scale(modul, tooth_number, R, r, d, n)
 * @brief Scale an epitrochoid to the requested tooth pitch.
 * @param modul {number > 0} Tooth module in mm.
 * @param tooth_number {integer >= 3} Number of teeth.
 * @param R {number > 0, default 3} Fixed-circle ratio.
 * @param r {number > 0, default 1} Rolling-circle ratio.
 * @param d {number >= 0, default 2} Pen offset ratio in the unit model.
 * @param n {integer >= 1, default 720} Number of samples used for arc length.
 * @return {number} Curve scale in mm.
 */
function _cg_epitrochoid_scale(modul,tooth_number,R=3,r=1,d=2,n=720) = _cg_trochoid_scale_from_points(modul,tooth_number,_cg_epitrochoid_points(R,r,d,n));
/***
 * @function _cg_epitrochoid_radius(R, r, d, theta)
 * @brief Evaluate the radial distance of the unit epitrochoid.
 * @param R {number > 0} Fixed-circle ratio.
 * @param r {number > 0} Rolling-circle ratio.
 * @param d {number >= 0} Pen offset ratio.
 * @param theta {angle} Curve parameter in degrees.
 * @return {number} Unit-curve radius.
 */
function _cg_epitrochoid_radius(R,r,d,theta) = _cg_trochoid_radius_from_point(_cg_epitrochoid_point(R,r,d,theta));
/***
 * @function _cg_epitrochoid_curve_radius(scale, R, r, d, theta)
 * @brief Evaluate a scaled epitrochoid radius.
 * @param scale {number > 0} Curve scale in mm.
 * @param R {number > 0} Fixed-circle ratio.
 * @param r {number > 0} Rolling-circle ratio.
 * @param d {number >= 0} Pen offset ratio.
 * @param theta {angle} Curve parameter in degrees.
 * @return {number} Radius in mm.
 */
function _cg_epitrochoid_curve_radius(scale,R,r,d,theta) = _cg_trochoid_curve_radius_from_point(scale,_cg_epitrochoid_point(R,r,d,theta));
/***
 * @function _cg_epitrochoid_points_scaled(scale, R, r, d, n)
 * @brief Sample a scaled epitrochoid curve.
 * @param scale {number > 0} Curve scale in mm.
 * @param R {number > 0} Fixed-circle ratio.
 * @param r {number > 0} Rolling-circle ratio.
 * @param d {number >= 0} Pen offset ratio.
 * @param n {integer >= 1, default 720} Number of samples.
 * @return {array} Closed list of sampled Cartesian points in mm.
 */
function _cg_epitrochoid_points_scaled(scale,R,r,d,n=720) = _cg_trochoid_points_scaled_from_points(scale,_cg_epitrochoid_points(R,r,d,n));
